version: '3.7'
networks:
  overlay-net:
    external: true      
    driver: overlay
services:
  rs:
    image: iudx/rs-depl:latest
    volumes:
      - ./secrets/credentials/all-verticles-configs/config-depl.json:/usr/share/app/secrets/credentials/all-verticles-configs/config.json
    expose:
      - "80"
      - "9000"
    networks: 
      - overlay-net
